services:
  - type: web
    name: dave-md-v1-pairing
    env: node
    plan: free
    branch: main

    buildCommand: npm install
    startCommand: node index.js

    envVars:
      - key: SESSION_ID
        sync: false
      - key: BOT_NAME
        value: Dave-Md-V1
      - key: OWNER_NUMBER
        value: 254104260236
      - key: OWNER_NAME
        value: Gifted Dave
      - key: PREMIUM_NUMBER
        value: 254104260236
      - key: GITHUB_USERNAME
        value: gifteddaves
      - key: WEBSITE_URL
        value: https://youtube.com/@gifteddave
      - key: WHATSAPP_CHANNEL
        value: https://whatsapp.com/channel/0029VbApvFQ2Jl84lhONkc3k
      - key: MESSAGE
        value: ✅ Session linked successfully to Dave-Md-V1
      - key: PORT
        value: 3000
      - key: MONGO_URI
        sync: false
      - key: HEROKU_API_KEY
        sync: false
